# Generated by Django 6.0.2 on 2026-04-15 22:56

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, error_messages={'max_length': 'Name cannot exceed 100 characters.'}, max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters long.')])),
                ('city', models.CharField(blank=True, error_messages={'max_length': 'City cannot exceed 100 characters.'}, max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='City must be at least 2 characters long.')])),
                ('birthday', models.DateField(blank=True, null=True, validators=[accounts.models.validate_birthday])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only JPG and PNG files are allowed.')])),
                ('favorite_games', models.ManyToManyField(blank=True, to='games.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
