# Generated by Django 6.0.2 on 2026-03-16 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(error_messages={'blank': 'Review text cannot be empty.'})),
                ('author', models.CharField(error_messages={'blank': 'Author name is required.', 'max_length': 'Author name cannot exceed 100 characters.'}, max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating cannot be lower than 1.'), django.core.validators.MaxValueValidator(5, message='Rating cannot be higher than 5.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game')),
            ],
        ),
    ]
