# Generated by Django 6.0.2 on 2026-03-16 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Game name is required', 'max_length': 'Game name must be less than 100 characters', 'unique': 'A game with this name already exists.'}, help_text='Enter a unique game name (at least 3 characters).', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('release_date', models.DateField(help_text='Select the official release date.')),
                ('description', models.TextField(error_messages={'blank': 'Description is required.'}, help_text='Write a detailed description (at least 10 characters).', validators=[django.core.validators.MinLengthValidator(10)])),
                ('image_url', models.URLField(blank=True, help_text='Optional: Provide an image URL for the game.', null=True)),
                ('genres', models.ManyToManyField(to='genres.genre')),
                ('platforms', models.ManyToManyField(to='platforms.platform')),
            ],
        ),
    ]
