# Generated by Django 6.0.2 on 2026-02-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
