# Generated by Django 6.0.2 on 2026-02-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
