# Generated by Django 6.0.2 on 2026-02-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_genre_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(error_messages={'blank': 'Game name is required', 'max_length': 'Game name must be less than 100 characters'}, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='games.platform'),
        ),
    ]
