# Generated by Django 6.0.2 on 2026-04-15 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Platform name is required', 'max_length': 'Platform name must be less than 50 characters', 'unique': 'A platform with this name already exists.'}, help_text='Enter a unique platform name (at least 3 characters).', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.URLField(blank=True, help_text='Optional: Provide an image URL for the platform.', null=True)),
            ],
        ),
    ]
